"""phase1 core tables

Revision ID: 223dfe122f05
Revises: 
Create Date: 2026-05-01 01:29:27.688040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223dfe122f05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('lens_model', sa.String(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter', sa.String(), nullable=True),
    sa.Column('focal_mm', sa.Float(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_phash'), ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_sha256'), ['sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_photos_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_taken_at'), ['taken_at'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('folders', sa.Text(), nullable=False),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('new_photos', sa.Integer(), nullable=False),
    sa.Column('changed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('eval_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_evaljobs_state_prio', ['state', 'priority', 'enqueued_at'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_lang', sa.String(), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('color_analysis', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('idx_eval_photo_model', ['photo_id', 'model_id', 'created_at'], unique=False)

    op.create_table('photo_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('nas_id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nas_id', 'path', name='uq_nas_path')
    )
    with op.batch_alter_table('photo_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_paths_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_paths_photo_id'))

    op.drop_table('photo_paths')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('idx_eval_photo_model')

    op.drop_table('evaluations')
    with op.batch_alter_table('eval_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_evaljobs_state_prio')

    op.drop_table('eval_jobs')
    op.drop_table('settings')
    op.drop_table('scan_jobs')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_taken_at'))
        batch_op.drop_index(batch_op.f('ix_photos_state'))
        batch_op.drop_index(batch_op.f('ix_photos_sha256'))
        batch_op.drop_index(batch_op.f('ix_photos_phash'))

    op.drop_table('photos')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
