"""advanced_reviews table

Revision ID: 48194c686472
Revises: a5f7fcce115e
Create Date: 2026-05-02 20:59:33.787797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48194c686472'
down_revision: Union[str, Sequence[str], None] = 'a5f7fcce115e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('user_tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advanced_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advanced_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_advanced_reviews_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advanced_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_reviews_photo_id'))
        batch_op.drop_index(batch_op.f('ix_advanced_reviews_created_at'))

    op.drop_table('advanced_reviews')
    # ### end Alembic commands ###
