"""add embeddings table

Revision ID: 8df49cc1998d
Revises: 223dfe122f05
Create Date: 2026-05-01 11:57:44.691027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df49cc1998d'
down_revision: Union[str, Sequence[str], None] = '223dfe122f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'model_id', 'model_version', name='uq_emb_photo_model')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_photo_id'))

    op.drop_table('embeddings')
    # ### end Alembic commands ###
